### ISSUE TITLE
Update gocql dependency

### ISSUE THREAD

**Issue by bhisey** [datastax/gocql-astra#15] opened 2023-09-28 18:11 UTC
We have implemented some of the fixes on the latest version of gocql, and we forgot to update the gocql version in gocql-astra. The issue is to get it updated to the latest

```
require (
	github.com/datastax/cql-proxy v0.1.4
	github.com/gocql/gocql v1.2.1-0.20220825062323-ce100a15a689 ### Update to latest
)
```

**Comment by absurdfarce** [comment] 2023-09-28 18:38
Dupe of #10 ?

**Comment by bhisey** [comment] 2023-09-28 18:40
Looks like it, just need to update to the latest 1.6.0 now.

**Comment by joao-r-reis** [comment] 2023-09-29 15:05
Oh that's my bad, I thought we didn't have an issue yet, I'll close this as a duplicate.

**Closed as not planned by joao-r-reis** 2023-09-29 15:05 UTC
Labels: duplicate
